### ISSUE TITLE
PHP Fatal error:  Uncaught InvalidArgumentException: $tagHandling must be of type String in V2 of DeepLLibrar

### ISSUE THREAD

**Issue by cappadaan** [baby-markt/deepl-php-lib#18]
Since the last update I got an fatal error:

PHP Fatal error:  Uncaught InvalidArgumentException: $tagHandling must be of type String in V2 of DeepLLibrary in /var/www/vhosts/ictergezocht.nl/httpdocs/vendor/babymarkt/deepl-php-lib/src/DeepL.php:136

**Comment by arkadiusjonczek** [comment]
@cappadaan Update your code that your `translate(..)` call uses a string instead of array as $tagHandling parameter. 

If you don't want to update your code you can use the old v1 in your project. Set the version of the package to `^v1.1.0` in your `composer.json` and run `composer update`.

Good Luck.

**Comment by VimS** [comment]
You can follow the Recommendations of @arkadiusjonczek.

Breaking Changes were mentioned in the Changelog:
https://github.com/Baby-Markt/deepl-php-lib/blob/master/CHANGELOG.md#changed
